pantalla: 
 ancho: 1000
 alto: 700

configuracion:
 vel_personaje: 1
 margen_scroll: 30

tipos:
 - nombre: barraca
   imagen: img/1elfos/ARQUERIA.png
   icono:  img/1elfos/icon-arqueria.bmp
   ancho_base: 4
   alto_base: 4
   pixel_ref_x: -90
   pixel_ref_y: 360
   raza: Elfo
   velocidad_de_construccion: 30
   oro: 50
   piedra: 50
   madera: 50

 - nombre: arqueriaElfos
   imagen: img/1elfos/ARQUERIA.png
   icono:  img/1elfos/icon-arqueria.bmp
   ancho_base: 4
   alto_base: 4
   pixel_ref_x: -90
   pixel_ref_y: 360
   raza: Elfo   

 - nombre: caballeriaElfos
   imagen: img/1elfos/CABALLERIA.png
   icono:  img/1elfos/icon-caballeria.bmp
   ancho_base: 3
   alto_base: 3
   pixel_ref_x: -70
   pixel_ref_y: 320
   raza: Elfo
   velocidad_de_construccion: 20

 - nombre: centrocivicoElfos
   imagen: img/1elfos/CENTRO-CIVICO.png
   ancho_base: 4
   alto_base: 4
   pixel_ref_x: -90
   pixel_ref_y: 270
   raza: Elfo

 - nombre: molElfos
   imagen: img/1elfos/MOLINO.png
   icono: img/1elfos/icon-molino.bmp
   ancho_base: 2
   alto_base: 2
   pixel_ref_x: -50
   pixel_ref_y: 80
   raza: Elfo
   velocidad_de_construccion: 20

 - nombre: centroCivicoHobbit
   imagen: img/2hobbit/CENTRO-CIVICO.png
   ancho_base: 5
   alto_base: 5
   pixel_ref_x: -145
   pixel_ref_y: 120
   raza: Hobbit
   velocidad_de_construccion: 20

 - nombre: cuartelHobbit
   imagen: img/2hobbit/CUARTEL.png
   ancho_base: 4
   alto_base: 4
   pixel_ref_x: -100
   pixel_ref_y: 80
   raza: Hobbit
   velocidad_de_construccion: 20

 - nombre: banderaHobbit
   imagen: img/2hobbit/bandera/flag.png
   ancho_base: 1
   alto_base: 1
   pixel_ref_x: 25
   pixel_ref_y: 0
   raza: Hobbit

 - nombre: escuderiaHumano
   imagen: img/3humanos/ESCUDERIA.png
   ancho_base: 4
   alto_base: 4
   pixel_ref_x: -125
   pixel_ref_y: 120
   raza: Humano
   velocidad_de_construccion: 20

 - nombre: centroCivicoHumano
   imagen: img/3humanos/CENTRO-CIVICO.png
   ancho_base: 5
   alto_base: 5
   pixel_ref_x: -125
   pixel_ref_y: 120
   raza: Humano
   velocidad_de_construccion: 20

 - nombre: caballeriaHumano
   imagen: img/3humanos/CABALLERIA.png
   ancho_base: 4
   alto_base: 4
   pixel_ref_x: -115
   pixel_ref_y: 130
   raza: Humano
   velocidad_de_construccion: 20

 - nombre: banderaHumano
   imagen: img/3humanos/bandera/flag.png
   ancho_base: 1
   alto_base: 1
   pixel_ref_x: -5
   pixel_ref_y: 70
   raza: Humano

 - nombre: molinoMordor
   imagen: img/4mordor/MOLINO.png
   ancho_base: 3
   alto_base: 3
   pixel_ref_x: -50
   pixel_ref_y: 75
   fps: 6
   delay: 1

 - nombre: cuartelMordor
   imagen: img/4mordor/CUARTEL.png
   ancho_base: 5
   alto_base: 5
   pixel_ref_x: -140
   pixel_ref_y: 120
   velocidad_de_construccion: 20

 - nombre: centroCivicoMordor
   imagen: img/4mordor/CENTRO-CIVICO.png
   ancho_base: 5
   alto_base: 5
   pixel_ref_x: -150
   pixel_ref_y: 450

 - nombre: cuartelBestiaMordor
   imagen: img/4mordor/CUARTEL-ESPECIAL.png
   ancho_base: 3
   alto_base: 3
   pixel_ref_x: -60
   pixel_ref_y: 60
   velocidad_de_construccion: 20

 - nombre: banderaMordor
   imagen: img/4mordor/bandera/flag.png
   ancho_base: 1
   alto_base: 1
   pixel_ref_x: 20
   pixel_ref_y: 45

 - nombre: gandalf
   imagen: img/2hobbit/gandalf/WALK.png
   imagen_quieto: img/2hobbit/gandalf/STAND.png
   imagen_atacar: img/2hobbit/gandalf/ATACK.png
   fps: 4
   delay: 0
   velocidad: 25
   vida: 50
   armadura: 10
   construccion: 10
   recoleccion: 10   
   fuerza: 10
   raza: Elfo
   edificio_constructor: barraca
   oro: 50
   comida: 50

 - nombre: wheel
   imagen: img/2hobbit/wheel.png
   ancho_base: 1
   alto_base: 2
   pixel_ref_x: -47
   pixel_ref_y: 50
   fps: 20
   delay: 1

 - nombre: herreria
   imagen: img/dibujo_dinamico/mirador.png
   pixel_ref_x: 60
   pixel_ref_y: 50   
   fps: 20
   delay: 50

 - nombre: pino
   imagen: img/dibujo_estatico/arbol/pinetree.png
   pixel_ref_x: 85
   pixel_ref_y: 88

 - nombre: church
   imagen: img/dibujo_estatico/construcciones/church.png
   pixel_ref_x: 60
   pixel_ref_y: 52

 - nombre: oro
   imagen: img/extras/terrain/gold.png
   pixel_ref_x: 10
   pixel_ref_y: 0 

 - nombre: piedra
   imagen: img/extras/terrain/roca/roca1.png
   pixel_ref_x: 10
   pixel_ref_y: 3

 - nombre: madera
   imagen: img/extras/terrain/arboles/arbol1.png
   pixel_ref_x: 16
   pixel_ref_y: 120

 - nombre: firestation
   imagen: img/dibujo_estatico/construcciones/firestation.png
   pixel_ref_x: 0
   pixel_ref_y: 44

 - nombre: arbol
   imagen: img/dibujo_estatico/arbol/firtree.png
   pixel_ref_x: 20
   pixel_ref_y: 45

escenario:
 nombre: orleans
 size_x: 100
 size_y: 100
 entidades: 
  - { x : 0, y: 5, tipo: madera }
  - { x : 10, y: 10, tipo: banderaMordor }
  - { x : 40, y: 6, tipo: church }
  - { x : 40, y: 0, tipo: herreria }
  - { x : 40, y: 4, tipo: wheel }
  - { x : 30, y: 10, tipo: barraca }
  - { x : 30, y: 0, tipo: firestation }
  - { x : 90, y: 90, tipo: molElfos }

