pantalla: 
 ancho: 1000
 alto: 700

configuracion:
 vel_personaje: 1
 margen_scroll: 30

tipos:
 - nombre: arqueriaElfos
   imagen: img/1elfos/ARQUERIA.png
   icono:  img/1elfos/icon-arqueria.bmp
   ancho_base: 4
   alto_base: 4
   pixel_ref_x: -90
   pixel_ref_y: 360
   vida: 50
   raza: Elfo  
   velocidad_de_construccion: 30
   oro: 164
   piedra: 47
   madera: 82   

 - nombre: caballeriaElfos
   imagen: img/1elfos/CABALLERIA.png
   icono:  img/1elfos/icon-caballeria.bmp
   ancho_base: 3
   alto_base: 3
   pixel_ref_x: -70
   pixel_ref_y: 320
   vida: 50
   raza: Elfo
   velocidad_de_construccion: 20
   oro: 180
   piedra: 45
   madera: 50 

 - nombre: centrocivicoElfos
   imagen: img/1elfos/CENTRO-CIVICO.png
   ancho_base: 4
   alto_base: 4
   pixel_ref_x: -90
   pixel_ref_y: 270
   vida: 50
   raza: Elfo

 - nombre: banderaElfos
   imagen: img/1elfos/bandera/bandera.png
   ancho_base: 1
   alto_base: 1
   pixel_ref_x: 10
   pixel_ref_y: 80
   vida: 1
   raza: Elfo

 - nombre: centroCivicoHobbit
   imagen: img/2hobbit/CENTRO-CIVICO.png
   ancho_base: 5
   alto_base: 5
   pixel_ref_x: -145
   pixel_ref_y: 120
   vida: 50
   raza: Hobbit

 - nombre: cuartelHobbit
   imagen: img/2hobbit/CUARTEL.png
   icono: img/2hobbit/icon-cuartel.bmp
   ancho_base: 4
   alto_base: 4
   pixel_ref_x: -100
   pixel_ref_y: 80
   vida: 50
   raza: Hobbit
   velocidad_de_construccion: 20
   oro: 55
   piedra: 50
   madera: 150 

 - nombre: casaGandalfHobbit
   imagen: img/2hobbit/CASA-GANDALF.png
   icono: img/2hobbit/icon-casa-gandalf.bmp
   ancho_base: 3
   alto_base: 3
   pixel_ref_x: -80
   pixel_ref_y: 85
   vida: 50
   raza: Hobbit
   velocidad_de_construccion: 20
   oro: 100
   madera: 300 

 - nombre: banderaHobbit
   imagen: img/2hobbit/bandera/flag.png
   ancho_base: 1
   alto_base: 1
   pixel_ref_x: 25
   pixel_ref_y: 0
   vida: 1
   raza: Hobbit

 - nombre: escuderiaHumano
   imagen: img/3humanos/ESCUDERIA.png
   icono: img/3humanos/icon-escuderia.bmp
   ancho_base: 4
   alto_base: 4
   pixel_ref_x: -125
   pixel_ref_y: 120
   vida: 50
   raza: Humano
   velocidad_de_construccion: 20
   oro: 28
   piedra: 175
   madera: 23 

 - nombre: centroCivicoHumano
   imagen: img/3humanos/CENTRO-CIVICO.png
   ancho_base: 5
   alto_base: 5
   pixel_ref_x: -125
   pixel_ref_y: 120
   vida: 50
   raza: Humano

 - nombre: caballeriaHumano
   imagen: img/3humanos/CABALLERIA.png
   icono: img/3humanos/icon-caballeria.bmp
   ancho_base: 4
   alto_base: 4
   pixel_ref_x: -115
   pixel_ref_y: 130
   vida: 50
   raza: Humano
   velocidad_de_construccion: 20
   oro: 50
   piedra: 200
   madera: 50 

 - nombre: banderaHumano
   imagen: img/3humanos/bandera/flag.png
   ancho_base: 1
   alto_base: 1
   pixel_ref_x: -5
   pixel_ref_y: 70
   vida: 1
   raza: Humano

 - nombre: cuartelMordor
   imagen: img/4mordor/CUARTEL.png
   icono: img/4mordor/icon-cuartel.bmp
   ancho_base: 5
   alto_base: 5
   pixel_ref_x: -140
   pixel_ref_y: 120
   vida: 50
   raza: Mordor
   velocidad_de_construccion: 20
   oro: 20
   piedra: 200
   madera: 20 

 - nombre: centroCivicoMordor
   imagen: img/4mordor/CENTRO-CIVICO.png
   ancho_base: 5
   alto_base: 5
   pixel_ref_x: -150
   pixel_ref_y: 450
   vida: 50
   raza: Mordor

 - nombre: cuartelBestiaMordor
   imagen: img/4mordor/CUARTEL-ESPECIAL.png
   icono: img/4mordor/icon-cuartel-especial.bmp
   ancho_base: 3
   alto_base: 3
   pixel_ref_x: -60
   pixel_ref_y: 60
   vida: 50
   raza: Mordor
   velocidad_de_construccion: 20
   oro: 150
   piedra: 300
   madera: 20 

 - nombre: banderaMordor
   imagen: img/4mordor/bandera/flag.png
   ancho_base: 1
   alto_base: 1
   pixel_ref_x: 20
   pixel_ref_y: 45
   vida: 1
   raza: Mordor

 - nombre: siervo
   imagen: img/1elfos/aldeano/WALK.png
   imagen_quieto: img/1elfos/aldeano/STAND.png
   imagen_atacar: img/1elfos/aldeano/ATACK.png
   icono: img/1elfos/aldeano/icon.bmp
   fps: 4
   delay: 0
   velocidad: 24
   vida: 30
   construccion: 15
   recoleccion: 15
   raza: Elfo
   edificio_constructor: centrocivicoElfos
   oro: 25
   comida: 25

 - nombre: arwen
   imagen: img/1elfos/heroe - Noblewoman/WALK.png
   imagen_quieto: img/1elfos/heroe - Noblewoman/STAND.png
   imagen_atacar: img/1elfos/heroe - Noblewoman/STAND.png
   icono: img/1elfos/heroe - Noblewoman/icon.bmp
   fps: 4
   delay: 0
   velocidad: 25
   vida: 100
   raza: Elfo
   edificio_constructor: centrocivicoElfos

 - nombre: legolas
   imagen: img/1elfos/legolas/WALK.png
   imagen_quieto: img/1elfos/legolas/STAND.png
   imagen_atacar: img/1elfos/legolas/ATACK.png
   icono: img/1elfos/legolas/icon.bmp
   fps: 4
   delay: 0
   velocidad: 24
   vida: 100
   fuerza: 40
   armadura: 15
   raza: Elfo
   edificio_constructor: arqueriaElfos
   oro: 50
   comida: 50
   rango: 10 

 - nombre: cirdan
   imagen: img/1elfos/legolas a caballo/WALK.png
   imagen_quieto: img/1elfos/legolas a caballo/STAND.png
   imagen_atacar: img/1elfos/legolas a caballo/ATACK.png
   icono: img/1elfos/legolas a caballo/icon.bmp
   fps: 4
   delay: 0
   velocidad: 24
   vida: 85
   fuerza: 35
   armadura: 15
   raza: Elfo
   edificio_constructor: caballeriaElfos
   oro: 200
   piedra: 100
   comida: 80

 - nombre: hobbit
   imagen: img/2hobbit/frodo-aldeano/WALK.png
   imagen_quieto: img/2hobbit/frodo-aldeano/STAND.png
   imagen_atacar: img/2hobbit/frodo-aldeano/ATACK.png
   icono: img/2hobbit/frodo-aldeano/icon.bmp
   fps: 4
   delay: 0
   velocidad: 30
   vida: 30
   construccion: 10
   recoleccion: 15
   raza: Hobbit
   edificio_constructor: centroCivicoHobbit
   oro: 25
   comida: 25

 - nombre: enano
   imagen: img/2hobbit/enano/WALK.png
   imagen_quieto: img/2hobbit/enano/STAND.png
   imagen_atacar: img/2hobbit/enano/ATACK.png
   icono: img/2hobbit/enano/icon.bmp
   fps: 4
   delay: 0
   velocidad: 24
   vida: 80
   fuerza: 20
   armadura: 20
   raza: Hobbit
   edificio_constructor: cuartelHobbit
   oro: 50
   piedra: 50
   madera: 50
   comida: 50

 - nombre: gandalf
   imagen: img/2hobbit/gandalf/WALK.png
   imagen_quieto: img/2hobbit/gandalf/STAND.png
   imagen_atacar: img/2hobbit/gandalf/ATACK.png
   icono: img/2hobbit/gandalf/icon.bmp
   fps: 4
   delay: 0
   velocidad: 18
   vida: 70
   fuerza: 200
   armadura: 15
   raza: Hobbit
   edificio_constructor: casaGandalfHobbit
   oro: 500
   madera: 100
   comida: 100

 - nombre: aragon
   imagen: img/2hobbit/heroe/WALK.PNG
   imagen_quieto: img/2hobbit/heroe/STAND.png
   imagen_atacar: img/2hobbit/heroe/STAND.png
   icono: img/2hobbit/heroe/icon.bmp
   fps: 4
   delay: 0
   velocidad: 25
   vida: 100
   raza: Hobbit
   edificio_constructor: centroCivicoHobbit

 - nombre: aldeano
   imagen: img/3humanos/aldeano/WALK.png
   imagen_quieto: img/3humanos/aldeano/STAND.png
   imagen_atacar: img/3humanos/aldeano/ATACK.png
   icono: img/3humanos/aldeano/icon.bmp
   fps: 4
   delay: 0
   velocidad: 22
   vida: 25
   construccion: 10
   recoleccion: 15
   raza: Humano
   edificio_constructor: centroCivicoHumano
   oro: 25
   comida: 25

 - nombre: soldado
   imagen: img/3humanos/caballero/WALK.png
   imagen_quieto: img/3humanos/caballero/STAND.png
   imagen_atacar: img/3humanos/caballero/ATACK.png
   icono: img/3humanos/caballero/icon.bmp
   fps: 4
   delay: 0
   velocidad: 18
   vida: 60
   fuerza: 10
   armadura: 10
   raza: Humano
   edificio_constructor: caballeriaHumano
   oro: 50
   comida: 50

 - nombre: knight
   imagen: img/3humanos/espadachin/WALK.png
   imagen_quieto: img/3humanos/espadachin/STAND.png
   imagen_atacar: img/3humanos/espadachin/ATACK.png
   icono: img/3humanos/espadachin/icon.bmp
   fps: 4
   delay: 0
   velocidad: 22
   vida: 100
   fuerza: 40
   armadura: 30
   raza: Humano
   edificio_constructor: escuderiaHumano
   oro: 100
   piedra: 50
   comida: 80

 - nombre: king
   imagen: img/3humanos/Prince John - heroe/WALK.png
   imagen_quieto: img/3humanos/Prince John - heroe/STAND.png
   imagen_atacar: img/3humanos/Prince John - heroe/STAND.png
   icono: img/3humanos/Prince John - heroe/icon.bmp
   fps: 4
   delay: 0
   velocidad: 24
   vida: 100
   raza: Humano
   edificio_constructor: centroCivicoHumano

 - nombre: trasgo
   imagen: img/4mordor/aldeano/WALK.png
   imagen_quieto: img/4mordor/aldeano/STAND.png
   imagen_atacar: img/4mordor/aldeano/ATACK.png
   icono: img/4mordor/aldeano/icon.bmp
   fps: 4
   delay: 0
   velocidad: 30
   vida: 20
   construccion: 15
   recoleccion: 10
   raza: Mordor
   edificio_constructor: centroCivicoMordor
   oro: 25
   comida: 25

 - nombre: sauron
   imagen: img/4mordor/heroe mordor/WALK.png
   imagen_quieto: img/4mordor/heroe mordor/STAND.png
   imagen_atacar: img/4mordor/heroe mordor/STAND.png
   icono: img/4mordor/heroe mordor/icon.bmp
   fps: 4
   delay: 0
   velocidad: 30
   vida: 100
   raza: Mordor
   edificio_constructor: centroCivicoMordor

 - nombre: orco
   imagen: img/4mordor/orco/WALK.png
   imagen_quieto: img/4mordor/orco/STAND.png
   imagen_atacar: img/4mordor/orco/ATACK.png
   icono: img/4mordor/orco/icon.bmp
   fps: 4
   delay: 0
   velocidad: 25
   vida: 20
   fuerza: 8
   armadura: 5
   raza: Mordor
   edificio_constructor: cuartelMordor
   oro: 20

 - nombre: troll
   imagen: img/4mordor/orco grande/WALK.png
   imagen_quieto: img/4mordor/orco grande/STAND.png
   imagen_atacar: img/4mordor/orco grande/ATACK.png
   icono: img/4mordor/orco grande/icon.bmp
   fps: 6
   delay: 0
   velocidad: 10
   vida: 200
   fuerza: 100
   armadura: 30
   raza: Mordor
   edificio_constructor: cuartelBestiaMordor
   oro: 200
   piedra: 100
   comida: 200

 - nombre: oro
   imagen: img/extras/terrain/gold.png
   pixel_ref_x: 10
   pixel_ref_y: 0 

 - nombre: piedra
   imagen: img/extras/terrain/roca/roca1.png
   pixel_ref_x: 10
   pixel_ref_y: 3

 - nombre: comida
   imagen: img/extras/comida.png
   pixel_ref_x: 10
   pixel_ref_y: 3

 - nombre: madera
   imagen: img/extras/terrain/arboles/arbol1.png
   pixel_ref_x: -20
   pixel_ref_y: 200

 - nombre: arbol
   imagen: img/extras/terrain/arboles/arbol1.png
   pixel_ref_x: 20
   pixel_ref_y: 45
   vida: 50

escenario:
 nombre: orleans
 size_x: 100
 size_y: 100
 entidades: 
  - { x : 0, y: 5, tipo: madera }

